version: '3.8'
services: 
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb_container
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_DATABASE: "android_app_database"

    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb

volumes:
  mariadb_data:
    driver: local

  #node-app:
  #  build: 
  #    context: .
  #  ports:
  #    - '3000:3000'
  #  depends_on:
  #    - mariadb